[package]
name = "rustymicrobit"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
nrf52833-hal = "0.19.0"
rtt-target = "0.6.2"
embedded-hal = "1.0.0"
